### ISSUE TITLE
could you please provide some documentation

### ISSUE THREAD

**Issue by cordoval** [hostnet/dead#4]
it looks very interesting and useful please share more

**Comment by hboomsma** [comment]
Hi cordoval, I'll try to get some time for updating the docs and visualization tools. Also see my answer on issue #5. The project is described [here](http://repository.tudelft.nl/assets/uuid:2bee12f5-22da-45fc-9576-c61808562a78/boomsma2012dead.pdf) and in this [paper](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6405314) (unfortunately not free)

**Comment by cordoval** [comment]
thanks I got it now
